"""empty message

Revision ID: aabe6b36869c
Revises: 34fdf17abf65
Create Date: 2024-10-18 00:12:29.369486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aabe6b36869c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('cpf_cnpj', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('total_area', sa.Integer(), nullable=False),
    sa.Column('agricultural_area', sa.Integer(), nullable=False),
    sa.Column('vegetation_area', sa.Integer(), nullable=False),
    sa.Column('farming_options', sa.JSON(), nullable=True),
    sa.Column('insert_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cpf_cnpj', name=op.f('farmer_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer')
    # ### end Alembic commands ###
